// keys.js - figure out what set of credentials to return...
  // whether we're in prod or dev environment...

// on heroku -> environment variable -> set to string === 'production'
if (process.env.NODE_ENV === 'production') {
  // return prod set of keys...
  module.exports = require('./prod');
} else {
  // we in dev - return dev keys...
    // pull in dev keys and then immediately provide...
  module.exports = require('./dev');
}